### ISSUE TITLE
[5] MACHINE LEARNING - As a developer I want to optimize the preprocessing steps so that the modeling is easier for neural sequence model

### ISSUE THREAD

**Issue by localaization** [localaization/pentagrom#10]
**Description:**
We are evaluating the _A. Event-based Representation for Music_ of the document [MuseMorphose](https://arxiv.org/pdf/2105.04090.pdf). We need to check with Jaime this method.

**Documentation:**
From [MuseMorphose and example midi file.zip](https://github.com/localaization/pentagrom/files/10775087/MuseMorphose.and.example.midi.file.zip)

![Image](https://user-images.githubusercontent.com/122649944/220164008-9a5b2600-a1e8-4bd6-9e82-fe6dc1c742a9.png)

From [This Time with Feeling: Learning Expressive Musical Performance](https://arxiv.org/pdf/1808.03715.pdf)
The piano is used in this example

![Image](https://user-images.githubusercontent.com/122649944/220158076-0475cdf4-e095-4425-bb79-fdbe3525d96e.png)

From [SEQUENCE-TO-SEQUENCE PIANO TRANSCRIPTION WITH TRANSFORMERS](https://archives.ismir.net/ismir2021/paper/000030.pdf)

<img width="1056" alt="pentagrom-presentation-014" src="https://user-images.githubusercontent.com/1562701/220189612-cac9e19c-d4a3-4d4c-98e0-60bfceddb108.png">

From [MT3: MULTI-TASK MULTITRACK MUSIC TRANSCRIPTION](https://openreview.net/pdf?id=iMSjopcOn0p)
<img width="835" alt="pentagrom-presentation-013" src="https://user-images.githubusercontent.com/1562701/220189826-2419bb77-9d53-4add-b4e1-a24cb2a73e32.png">

From [Twitter](https://twitter.com/DrJimFan/status/1625167698866110464?s=20)
![Image](https://user-images.githubusercontent.com/1562701/220214134-a802fe9c-3f3d-429b-926b-a4e2b03a04a5.png)

### Piano mapping  
Does not univocally map any written note.
![Image](https://user-images.githubusercontent.com/1562701/220192017-0211db23-e32a-40e5-a1df-38ef94f9d310.png)

### Pentagrom mapping  
It maps univocally any written note.
![Image](https://user-images.githubusercontent.com/1562701/220192745-d9d33bb6-0639-4d68-adce-53f56110e5e4.png)

**Solution**

1. Read _A. Event-based Representation for Music_ chapter of the MuseMorphose doc.
2. Take a look at the documentation (in the section above).
3. Identify and check if the variables and tokens are suitable for the pentagrom structure.
4. Map the identified elements which are suitable to the actual pentagrom elements.

**Q&A:**
1. Check this paper and see if a 7x3 matrix instead of 8x1 make sense and solve the questions: [Piano Genie] (https://arxiv.org/pdf/1810.05246.pdf)

**Definition of Done:**
To have an agreement whether or not section "A. Event-based Representation for Music" from MuseMorphose is a good approximation.

**Comment by localaization** [comment]
From [This Time with Feeling: Learning Expressive Musical Performance](https://arxiv.org/pdf/1808.03715.pdf)

![Image](https://user-images.githubusercontent.com/122649944/220158076-0475cdf4-e095-4425-bb79-fdbe3525d96e.png)

**Comment by TuWebO** [comment]
There is a lot of information that we could potentially get from:
https://magenta.tensorflow.org/

I didn't know about it until now.
I will take note about some interesting links:
https://magenta.tensorflow.org/ddsp-vst-blog
https://openreview.net/forum?id=B1x1ma4tDr&noteId=lcOwh022Vta
https://github.com/magenta/mt3
https://archives.ismir.net/ismir2021/paper/000030.pdf
https://openreview.net/pdf?id=iMSjopcOn0p

**Comment by TuWebO** [comment]
I've updated the documentation with the latest articles I've seen. I will meet Jaime tomorrow and leave this task unassigned for now.

**Comment by localaization** [comment]
Jaime and myself have been talking about this issue. We have red the A. Event-based Representation for Music from the document [MuseMorphose](https://arxiv.org/pdf/2105.04090.pdf), also another papers and [pianogenie](https://arxiv.org/pdf/1810.05246.pdf) project.
 We think the pentagrom system could have one main advantage:
- It can univocally map any note in the matrix to any written note in the stave, something that does not happen with the piano or any other music controller so far.

![Image](https://user-images.githubusercontent.com/122649944/220443725-02d7913c-167e-433f-bcd3-c4fff6c76591.jpg)


![Image](https://user-images.githubusercontent.com/122649944/220451831-69c7c2ec-e2c6-415f-9dbd-71c38d6af3dc.png)

![Image](https://user-images.githubusercontent.com/122649944/220443881-3bd6cd4f-37dc-4d86-bd19-fbb2908b2228.png)

**Comment by localaization** [comment]
@isamu-isozaki this is the task, if you think it is solved feel free to mark it as done, otherwise assign it to me and back to in progress.

**Comment by isamu-isozaki** [comment]
@localaization yup nice work! I think it's done. I think for machine learning, we just go through
your format -> remi -> model which should do the job. Possibly midi in between
