### ISSUE TITLE
[5] PROJECT - As a team I want the environment settings and tools configured so that the workflow is easier

### ISSUE THREAD

**Issue by localaization** [localaization/pentagrom#8]
**Description:**
This is a project involving people from different countries, we need the proper tools and communication channels for organizing the project.

**Documentation:**
- Discord channel: [Localaization - Discord - music-pentagrom-project](https://discord.gg/QQjG7PCr)
- Twitter account: [Localaization - Twitter](https://twitter.com/localaization)
- Discord Algovera: [Algovera - Discord](https://discord.gg/Mk5xSc4E)

**QA**
- Check github repo [https://github.com/localaization/pentagrom](https://github.com/localaization/pentagrom) and project [https://github.com/users/localaization/projects/1/views/1](https://github.com/users/localaization/projects/1/views/1) to be accesible by the members but make it only readable (or private) for non members.
- Check Discord channel is running and the channel is public accesible [Localaization - Music pentagrom channel](https://discord.gg/Z5GjyQKZ)

**DoD:**
- Agreement about tools.
- Agreement about tracking.
- Agreement about meetings and work methodology.
- Have the tools and workflow running as we agreed.

**Comment by TuWebO** [comment]
Created all accounts, created the project in github, added some issues and created a "test" account in toggl. Next step will be validate the tools with the team, probably this weekend.

**Comment by TuWebO** [comment]
Repo, discord channel and basic team has been set up. Closing this taks.
